config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'experiences#index'
  resources :experiences do
    resources :bookings, only: [:new,:create, :show, :destroy]
  end
  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :start_date, :end_date, presence: true
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :name, :description, :price, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :experiences
  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController
  before_action :set_experience, only: [:new, :create, :show]
  before_action :set_booking, only: [:show]

  # def index
  #   @booking = booking.where(user: current_user)
  # end

  def index
    # @user = User.find(session[:user_id])
    @bookings = Booking.where(user_id: current_user.id)
  end

  # def index
  #   raise
  #   @user = User.find(session[:id])
  #   @booking = @user.booking
  # end


  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(bookings_params)
    @booking.experience = @experience
    @booking.user = current_user
    @booking.save
    redirect_to experience_booking_path(@experience, @booking)
  end

  def show
    # @user = User.find(session[:user_id])
    # raise
    # @booking = Booking.where(user_id: current_user)
    # @booking = booking.where(user: current_user)
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_experience
   @experience = Experience.find(params[:experience_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def my_booking

  end


end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    if params[:query].present?
      @experiences = Experience.where("city ILIKE ?", "%#{params[:query]}%")
    else
      @experiences = Experience.all
    end
  end

  def show
    @experience = Experience.find(params[:id])
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      redirect_to experiences_path, notice: 'Experience was successfully created.'
    else
      render :new
    end
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    @experience = Experience.find(params[:id])
    @experience.update(experience_params)
    redirect_to experience_path(@experience)
  end

  def destroy
    @experience = Experience.find(params[:id])
    @experience.destroy
    redirect_to experiences_path, status: :see_other

  end

  private

  def experience_params
    params.require(:experience).permit(:name, :city, :price, :description, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="experiences-container">
  <h1 class="py-4">Your bookings!</h1>

  <div class="experience-cards">
    <% @bookings.each do |booking| %>
      <div class="card-trip">
        <%= link_to experience_path(booking.experience) do %>
          <%= cl_image_tag booking.experience.photo.key, crop: :fill, class:"img"%>
          <div class="card-trip-infos">
            <div>
              <%= booking.experience.name %>
              <p><%= booking.experience.description %></p>
            </div>
          <h2 class="card-trip-pricing"><%= booking.start_date %> - <%= booking.end_date %></h2>
          <%= cl_image_tag booking.experience.user.photo.key, class:"card-trip-user avatar-bordered" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="calcontainer">
        <h3>Make your booking here!</h3>
        <%= simple_form_for [@experience,@booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
          <%= f.button :submit, class: 'btn-main' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="booking-confirmation">
  <h1 class="py-5">Your booking was successful!</h1>


  <div class="details">
    <h4 class="details-headline py-3">Your Booking Details....</h4>
    <div class="details-experience">
      <p class="experience-age"><svg style="width:24px;height:24px" class="detail-icon" viewBox="0 0 24 24">
      <path fill="currentColor" d="M13,2.05V5.08C16.39,5.57 19,8.47 19,12C19,12.9 18.82,13.75 18.5,14.54L21.12,16.07C21.68,14.83 22,13.45 22,12C22,6.82 18.05,2.55 13,2.05M12,19A7,7 0 0,1 5,12C5,8.47 7.61,5.57 11,5.08V2.05C5.94,2.55 2,6.81 2,12A10,10 0 0,0 12,22C15.3,22 18.23,20.39 20.05,17.91L17.45,16.38C16.17,18 14.21,19 12,19Z"></path>
      </svg>   <%= @experience.name %></p>
      <p class="experience-city"><svg style="width:24px;height:24px" class="detail-icon" viewBox="0 0 24 24">
      <path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z"></path>
      </svg>   <%=    @experience.city %></p>
      <p class="experience-type"><svg style="width:24px;height:24px" class="detail-icon" viewBox="0 0 24 24">
      <path fill="currentColor" d="M19 2L14 6.5V17.5L19 13V2M6.5 5C4.55 5 2.45 5.4 1 6.5V21.16C1 21.41 1.25 21.66 1.5 21.66C1.6 21.66 1.65 21.59 1.75 21.59C3.1 20.94 5.05 20.5 6.5 20.5C8.45 20.5 10.55 20.9 12 22C13.35 21.15 15.8 20.5 17.5 20.5C19.15 20.5 20.85 20.81 22.25 21.56C22.35 21.61 22.4 21.59 22.5 21.59C22.75 21.59 23 21.34 23 21.09V6.5C22.4 6.05 21.75 5.75 21 5.5V19C19.9 18.65 18.7 18.5 17.5 18.5C15.8 18.5 13.35 19.15 12 20V6.5C10.55 5.4 8.45 5 6.5 5Z"></path>
      </svg>   <%= @booking.start_date %></p>
      <p class="experience-purpose"><svg style="width:24px;height:24px" class="detail-icon" viewBox="0 0 24 24">
      <path fill="currentColor" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12C22,10.84 21.79,9.69 21.39,8.61L19.79,10.21C19.93,10.8 20,11.4 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4C12.6,4 13.2,4.07 13.79,4.21L15.4,2.6C14.31,2.21 13.16,2 12,2M19,2L15,6V7.5L12.45,10.05C12.3,10 12.15,10 12,10A2,2 0 0,0 10,12A2,2 0 0,0 12,14A2,2 0 0,0 14,12C14,11.85 14,11.7 13.95,11.55L16.5,9H18L22,5H19V2M12,6A6,6 0 0,0 6,12A6,6 0 0,0 12,18A6,6 0 0,0 18,12H16A4,4 0 0,1 12,16A4,4 0 0,1 8,12A4,4 0 0,1 12,8V6Z"></path>
      </svg>   <%= @booking.end_date %></p>
      <p class="experience-price">Total:   $<%= @experience.price %></p>
    </div>
  </div>
  <%= link_to 'Back to all experiences', experiences_path, class: 'btn-main my-2' %>
</div>

app/views/experiences/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for [@experience] do |f| %>
        <%= f.input :name %>
        <%= f.input :city %>
        <%= f.input :price %>
        <%= f.input :description %>
        <%= f.button :submit, class: 'btn-main'%>
      <% end %>
    </div>
  </div>
</div>

app/views/experiences/index.html.erb
<div id="image-container">
  <div class="banner">
    <div id="form-container">
      <%= form_tag experiences_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Where do you wanna experience..."
        %>
        <%= submit_tag "go..", class: "btn-main" %>
      <% end %>
    </div>
  </div>
</div>
<div class="experiences-container">
  <h1 class="py-4">Explore our experiences around you!</h1>

  <div class="experience-cards">
    <% @experiences.each do |experience| %>
      <div class="card-trip">
        <%= link_to experience_path(experience) do %>
          <%= cl_image_tag experience.photo.key, crop: :fill, class:"img"%>
          <div class="card-trip-infos">
            <div>
              <%= experience.name %>
              <p><%= experience.description %></p>
            </div>
          <h2 class="card-trip-pricing">$ <%= experience.price %></h2>
          <%= cl_image_tag experience.user.photo.key, class:"card-trip-user avatar-bordered" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container py-4">
  <h2>Create a new experience</h2>

  <%= simple_form_for [@experience] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :city %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class:'btn-main my-2' %>
    <%= link_to 'Back to all experiences', experiences_path, class: 'btn-main my-2' %>
  <% end %>
</div>

app/views/experiences/show.html.erb
<div class="final-container" >
  <div class="experience-detail-container">
    <%= cl_image_tag @experience.photo.key,width: 350, height: 300, crop: :fill, class:"img"%>
    <div class="experience-container">
      <div class="detail-container">
        <h1><%= @experience.name %></h1>
        <p><strong>| $<%= @experience.price %> | <%= @experience.city %></strong></p>
        <p><%= @experience.description %></p>
      </div>
      <div class="experience-price">
        <a class="m-2"><%= link_to "Book", new_experience_booking_path(@experience),class: 'btn-main' %></a>
        <% if current_user == @experience.user %>
          <a class="m-2"><%= link_to "Edit", edit_experience_path(@experience), :class=> 'btn-main'%></a>
          <a class="m-2"><%= link_to "Delete", experience_path(@experience), data: { turbo_method: :delete, turbo_confirm: "Are you sure"}, :class=> 'btn-main'%></a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>

    <title>Life20</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="css/bootstrap.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <div class="page-container">
      <div class="navbar-container"><%= render "components/navbar" %></div>
      <div class="content-container"><%= yield %></div>
      <p class="notice" style="margin: 0;"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="footer-container"><%= render "components/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>